# Generated by Django 4.0.4 on 2022-05-30 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id_nacionalidad', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Parentezco',
            fields=[
                ('id_parentezco', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=40)),
                ('vive', models.BooleanField()),
                ('id_nacionalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registrodefamiliares.nacionalidad')),
                ('id_parentezco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registrodefamiliares.parentezco')),
            ],
        ),
    ]
