# Generated by Django 4.0.4 on 2022-05-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodefamiliares', '0002_remove_familiar_id_nacionalidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nacionalidad', models.IntegerField(null=True)),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='familiar',
            name='numero_nacionalidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='familiar',
            name='telefono',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
